### ISSUE TITLE
Installation help?

### ISSUE THREAD

**Issue by TickledGrape** [SwiftOtter/AdvancedPricingBug#1]
I'm having issues installing this, I have copied the folder to the root of my magento and run the "composer" command, but this failed - I'm using SSH and a Bash Shell to run the command; but it's not working.

Is there a specific way to install this? Or a way I could understand as I'm fairly new to doing all of this.

Thanks.

**Comment by tjons** [comment]
Hey there! 

This module is designed to be installed through composer, so ensure you have that installed on your system: https://getcomposer.org/download/. Then, run `composer install swiftotter/advancedpricingbug` in your Magento 2 root directory. Once that's finished, you'll need to enable the module with `php bin/magento module:enable SwiftOtter_AdvancedPricingBug`. That should install and enable the module for your use.

Please let me know if you have any other questions!

**Comment by decorat1** [comment]
how can i fix it by manually 
bcs i bash shell and cant install composer

**Comment by JosephMaxwell** [comment]
Hello @decorat1. To fix it, I recommend copying the files (there are just a couple) and placing them into `app/code/SwiftOtter/AdvancedPricingBug`. Then, run the commands found in the README.

That should fix your problems.

**Comment by decorat1** [comment]
thanks for your answer 
but im new in magento please tell me step by step 
thank again from you

**Comment by decorat1** [comment]
i try it and show me 
Unknown module(s): 'SwiftOtter/AdvancedPricingBug'
or 
Unknown module(s): 'swiftotter/advanced-pricing-bug'

:(

**Comment by JosephMaxwell** [comment]
It would be helpful if you would share the exact commands you are running.
