### ISSUE TITLE
Module installed: still have error

### ISSUE THREAD

**Issue by yetimaan** [SwiftOtter/AdvancedPricingBug#2]
- Running Magento CE 2.1.7
- PHP 7.0.20

Still getting error when editing or creating a new product: The configuration parameter "componentType" is a required for "advanced_inventory_modal" component.

This is not an upgraded Magento install - the error showed up after the weekend.  I'm running the cron scripts below:

/usr/local/bin/php -d memory_limit=1024M /home/.../public_html/beta/bin/magento index:reindex
/usr/local/bin/php -d memory_limit=1024M /home/.../public_html/beta/bin/magento cron:run
/usr/local/bin/php -d memory_limit=1024M /home/.../public_html/beta/bin/magento cache:clean
/usr/local/bin/php -d memory_limit=1024M /home/.../public_html/beta/bin/magento cache:flush

Any idea where/what went wrong or why this patch isn't working?

**Comment by ghost** [comment]
@thomascblack interesting, I'm not sure off the top of my head, but this module is designed to fix the `Exception #0 (Magento\Framework\Exception\LocalizedException): The configuration parameter "componentType" is a required for "advanced_pricing_button" component` error, which looks different from the one you're receiving.

**Comment by yetimaan** [comment]
@tylerschade  Yep, that is different.  Here's the first line of the error output:

`a:4:{i:0;s:99:"The configuration parameter "componentType" is a required for "advanced_inventory_modal" component.";i:1;s:7195:"#0 /home/****/public_html/beta/vendor/magento/framework/View/Element/UiComponentFactory.php(362): Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem(Array, Array, false)`

**Comment by ghost** [comment]
Alright, so I'm going to encourage you to close this as it is unrelated to our module. Do you agree, or do you think it's related?

**Comment by yetimaan** [comment]
I really couldn't tell you if it's related or not.  If you think it is, I'll close.  No problem.
